-- CREATE TYPE trigger AS ENUM (
--     'Lack of sleep',
--     'Interrupted sleep',
--     'Anxiety',
--     'Caffeine',
--     'High humidity',
--     'Alcohol',
--     'Stress',
--     'Depressed mood',
--     'Strong smell',
--     'Processed food',
--     'Chocolate',
--     'Skipped beta blockers'
-- );

CREATE TABLE migraine_records (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    trigger TEXT NOT NULL,
    symptom TEXT NOT NULL,
    treatment TEXT NOT NULL,
    comment TEXT
);