CREATE TABLE migraine_records (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES migraine_users(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    location TEXT NOT NULL,
    time TEXT NOT NULL,
    onset TEXT NOT NULL,
    intensity INTEGER NOT NULL,
    trigger TEXT NOT NULL,
    symptom TEXT NOT NULL,
    treatment TEXT NOT NULL,
    comment TEXT
);